Add new KV feature gate: kvWithHostPassthroughCPU
kubevirt/hyperconverged-cluster-operator pull request #1037
Opened 2021-01-06 07:51 UTC by nunnatsa

Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**Release note**:

```release-note
Add new KV feature gate: kvWithHostPassthroughCPU
```

2021-01-06 09:23 UTC, nunnatsa commented
/test hco-e2e-upgrade-aws

2021-01-06 12:57 UTC, nunnatsa commented
/test hco-e2e-upgrade-aws

2021-01-06 13:29 UTC, enp0s3 requested changes

2021-01-06 13:29 UTC, enp0s3 commented on pkg/controller/operands/kubevirt.go
> +	kvWithHostPassthroughCPU = "WithHostPassthroughCPU"
Can we add `kvWithHostModelCPU = "WithHostModelCPU"? We need to manage them both.

2021-01-06 13:29 UTC, enp0s3 commented on pkg/controller/operands/kubevirt.go
> +		kvWithHostPassthroughCPU,
Following my previous comment, can we add `kvWithHostModelCPU` to the list?

2021-01-17 12:35 UTC, nunnatsa commented
/hold

2021-01-18 13:44 UTC, nunnatsa commented
Closed in favor of #1063

2021-01-18 13:44 UTC, closed without merging