Set DiskVerification memory usage limit in KubeVirt CR
kubevirt/hyperconverged-cluster-operator pull request #1435
Opened 2021-07-09 11:01 UTC by acardace

This sets the memory usage limit to a safe value, increasing it
from the default one specified in KubeVirt which can cause occasional
failures when KubeVirt is running on OpenShift.

Refer to https://github.com/kubevirt/kubevirt/pull/6005

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1979631
Signed-off-by: Antonio Cardace <acardace@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
Set DiskVerification memory usage limit in KubeVirt CR
```

2021-07-09 11:04 UTC, acardace commented
/hold

This PR is will not compile until https://github.com/kubevirt/kubevirt/pull/6005 is merged.

2021-07-09 11:05 UTC, acardace commented
/cc @tiraboschi

2021-07-22 08:27 UTC, nunnatsa requested changes
Please rebase after #1450 is merged

2021-07-22 08:28 UTC, acardace commented
> Please rebase after #1450 is merged

Yup, just waiting for that :+1: thank you!

2021-07-22 08:33 UTC, nunnatsa commented
> Yup, just waiting for that  thank you!

It's not merged yet :)

2021-07-22 12:45 UTC, acardace commented
/unhold

2021-07-22 14:02 UTC, nunnatsa requested changes
Please follow the inline comments to fix the unit tests, and also, in pkg/controller/operands/kubevirt_test.go, lines ~1118, change from
```golang
existingResource.Spec.Configuration.DeveloperConfiguration = &kubevirtv1.DeveloperConfiguration{
	FeatureGates: fgs,
}
```

to 
```golang
existingResource.Spec.Configuration.DeveloperConfiguration.FeatureGates = fgs
```

2021-07-23 08:16 UTC, acardace commented on pkg/controller/operands/kubevirt.go
> +	kvDiskVerificationMemoryLimit = resource.NewScaledQuantity(2, resource.Giga)
Hi @nunnatsa thanks for the review! I'm afraid this doesn't work as `ParseQuantity` returns `(resource.Quantity, error)` and we cannot deal with a error here.

2021-07-23 08:18 UTC, acardace commented on pkg/controller/operands/kubevirt_test.go
> +			Expect(foundResource.Spec.Configuration.DeveloperConfiguration.DiskVerification.MemoryLimit).Should(Equal(kvDiskVerificationMemoryLimit))
Changed, thanks!

2021-07-23 11:28 UTC, nunnatsa commented on pkg/controller/operands/kubevirt.go
> +	kvDiskVerificationMemoryLimit = resource.NewScaledQuantity(2, resource.Giga)
But since it's a valid constant string, we can ignore the error (this why the `_` is there).

2021-07-23 11:40 UTC, acardace commented on pkg/controller/operands/kubevirt.go
> +	kvDiskVerificationMemoryLimit = resource.NewScaledQuantity(2, resource.Giga)
gotcha, will change!

2021-07-23 12:33 UTC, acardace commented on pkg/controller/operands/kubevirt.go
> +			MemoryLimit: kvDiskVerificationMemoryLimit,
Done!

2021-07-23 13:22 UTC, nunnatsa commented
/override-bot

2021-07-23 14:50 UTC, merged