Serve virtctl binaries from cluster for disconnected environments
kubevirt/hyperconverged-cluster-operator pull request #1466
Opened 2021-08-04 12:33 UTC by erkanerol

**PLEASE DON'T REVIEW THIS PR UNTIL THIS MESSAGE IS DELETED**

Now, we are redirecting users to github.com download page
when they want to download virtctl binary. However, it doesn't
work in disconnected environment. Therefore, we are starting
serving the binaries from the cluster so that users can download it
in disconnected environments.

Signed-off-by: Erkan Erol <eerol@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note

```

2021-08-05 11:37 UTC, nunnatsa approved these changes
/approve

2021-08-08 06:18 UTC, nunnatsa commented
/retest

2021-08-12 12:18 UTC, tiraboschi commented
/retest

2021-08-16 20:51 UTC, nunnatsa commented
/retest

2021-08-17 04:47 UTC, nunnatsa commented
/retest

2021-08-17 05:34 UTC, nunnatsa requested changes
It seems that there is one problem that seems to be a real problem - maybe it's the reason why the installation fails? one of the `name` labels of the new **downloads** deployment, is with the **webhook** name.

In addition, all the rest of the comments are about the name of the new deployment/service/pod etc. : I found `downloads` to be too generic. please consider to rename it to something more specific. And also, the new image name is `virt-artifacts` and it's very different than the `downloads` or even `hco-cli-downloads` and I find it confusing - could we use a similar name that will show the connection between the image and the service/deployment/pod?

2021-08-17 05:34 UTC, nunnatsa commented on deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
> +          name: hyperconverged-cluster-webhook
should be something else. maybe `hyperconverged-cluster-cli-download`?

2021-08-17 05:34 UTC, nunnatsa commented on deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
> +        name: downloads
maybe `hco-cli-download`?

2021-08-17 05:34 UTC, nunnatsa commented on deploy/index-image/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
> +                name: downloads
maybe `hco-cli-download`?

2021-08-17 05:34 UTC, nunnatsa commented on deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
> +          name: hyperconverged-cluster-webhook
should be something else. maybe `hyperconverged-cluster-cli-download`?

2021-08-17 05:34 UTC, nunnatsa commented on deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
> +              name: downloads
maybe `hco-cli-download`?

2021-08-17 05:34 UTC, nunnatsa commented on deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
> +                name: downloads
maybe `hco-cli-download`?

2021-08-17 05:34 UTC, nunnatsa commented on deploy/operator.yaml
> +    name: downloads
maybe `hco-cli-download`?

2021-08-17 05:34 UTC, nunnatsa commented on deploy/operator.yaml
> +  name: downloads
maybe `hco-cli-download`?

2021-08-17 05:34 UTC, nunnatsa commented on deploy/operator.yaml
> +        name: downloads
maybe `hco-cli-download`?

2021-08-17 05:34 UTC, nunnatsa commented on hack/build-manifests.sh
> +DOWNLOADS_IMAGE=${DOWNLOADS_IMAGE:-quay.io/kubevirt/virt-artifacts-server:${CSV_VERSION}-unstable}
`HCO_DOWNLOAD_IMAGE`?

2021-08-17 05:34 UTC, nunnatsa commented on hack/build-manifests.sh
>  DIGEST_LIST="${DIGEST_LIST},${HCO_OPERATOR_IMAGE}|hyperconverged-cluster-operator,${HCO_WEBHOOK_IMAGE}|hyperconverged-cluster-webhook"
Add the download image to this list

2021-08-17 05:34 UTC, nunnatsa commented on pkg/components/components.go
> +	downloadsName = "downloads"
maybe `hco-cli-download`?

2021-08-17 05:34 UTC, nunnatsa commented on pkg/components/components.go
> +	DownloadsImage      string
`CliDownloadImage`?

2021-08-17 05:34 UTC, nunnatsa commented on pkg/components/components.go
> +				Label: getLabels(hcoNameWebhook, params.HcoKvIoVersion),
should be `Label: getLabels(downloadsName, params.HcoKvIoVersion),`

2021-08-17 05:34 UTC, nunnatsa commented on pkg/controller/operands/cliDownload.go
> +	downloadsServiceName = "downloads"
`cli-downloads`?

2021-08-18 13:41 UTC, erkanerol commented
/retest-required

2021-08-18 13:44 UTC, tiraboschi commented
wait for openshift-ci
/hold

2021-08-18 13:54 UTC, erkanerol commented
New PR: https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1487

2021-08-18 13:54 UTC, closed without merging