Remove old HCO metrics services and endpoints when upgrading
kubevirt/hyperconverged-cluster-operator pull request #1711
Opened 2022-01-17 16:25 UTC by machadovilaca

There is a bug when updating from v1.2.x to versions later than v1.4.x where services `hyperconverged-cluster-operator-metrics` and `hyperconverged-cluster-webhook-metrics`, and endpoint `hyperconverged-cluster-operator-metrics` are not being deleted. This PR ensures those objects are removed.

Signed-off-by: João Vilaça <jvilaca@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
Remove old HCO metrics services and endpoints when upgrading
```

2022-01-17 18:40 UTC, machadovilaca commented
/retest

2022-01-18 15:48 UTC, tiraboschi commented
/retest

2022-01-21 15:16 UTC, tiraboschi commented
/rebase

2022-01-22 08:56 UTC, tiraboschi commented
/rebase

2022-02-08 09:31 UTC, nunnatsa commented
/retest

2022-02-08 09:55 UTC, nunnatsa reviewed
I want to suggest something. Maybe, instead of going to the api-server each time to search for the services and the endpoint, converging the resources to object and so on, we can have a static list of these three objects, where we only need to loop over and delete its items? We can maybe also remove the deleted objects from the list so we could skip them next time, then this code will happen again only if the pod was restarted during upgrade.

@machadovilaca, what do you think?

2022-02-08 09:55 UTC, nunnatsa commented on pkg/controller/hyperconverged/hyperconverged_controller.go
> +		"hyperconverged-cluster-webhook-metrics",
please use constants

2022-02-08 09:55 UTC, nunnatsa commented on pkg/controller/hyperconverged/hyperconverged_controller.go
> +		"hyperconverged-cluster-operator-metrics",
should use the same constant as above

2022-02-08 09:55 UTC, nunnatsa commented on pkg/controller/hyperconverged/hyperconverged_controller.go
> +
I think `hcoutil.EnsureDeleted` already does this logic. Please check if we can remove these lines and the `getObj` function.

2022-02-08 09:56 UTC, nunnatsa commented on pkg/controller/hyperconverged/hyperconverged_controller_test.go
> +					"hyperconverged-cluster-webhook-metrics",
use constant from above comment

2022-02-08 09:57 UTC, nunnatsa commented on pkg/controller/hyperconverged/hyperconverged_controller_test.go
> +				}
It will work. I wonder if it won't be simpler just to add these two services as a golang structs.

2022-02-08 09:58 UTC, nunnatsa commented on pkg/controller/hyperconverged/hyperconverged_controller_test.go
> +				}
same

2022-02-08 09:59 UTC, nunnatsa commented on pkg/controller/hyperconverged/hyperconverged_controller_test.go
> +					}
again - it's only two services

2022-02-08 10:00 UTC, nunnatsa commented on pkg/controller/hyperconverged/hyperconverged_controller_test.go
> +					}
here too

2022-02-08 10:02 UTC, nunnatsa commented on pkg/controller/hyperconverged/hyperconverged_controller_test.go
> +				})
Please add a check to read back the endpoint and make sure it's not there.

2022-02-08 10:02 UTC, nunnatsa commented on pkg/controller/hyperconverged/hyperconverged_controller_test.go
> +					Expect(events.CheckEvents(serviceEvents)).To(BeTrue())
Please add a check to read back the services and make sure they are not there.

2022-02-08 10:09 UTC, nunnatsa commented on pkg/controller/hyperconverged/hyperconverged_controller.go
> +	return upgradePatched || oldMetricsSVCRemoved, nil
I believe this is not needed. This function returns `true` if the **`HyperConverged`** CR is modified, in order to requeue later. This is not neede when removing another resources, as services or endpoints. I think the `removeOldMetricsObjs` function should only return error, but not the boolean value.

2022-02-08 10:10 UTC, nunnatsa requested changes
Please review my comment.

2022-02-08 13:07 UTC, machadovilaca commented
@nunnatsa updated

2022-02-08 13:07 UTC, machadovilaca commented
/retest

2022-02-08 16:50 UTC, machadovilaca commented
/retest

2022-02-09 13:29 UTC, machadovilaca commented
/retest

2022-02-10 13:59 UTC, machadovilaca commented
/retest

2022-02-13 11:33 UTC, nunnatsa commented
@machadovilaca - the upgrade tests are failing because HCO dose not have permissions to list/get/delete endpoints. Please add the missing RBAC.

2022-02-13 11:36 UTC, nunnatsa commented on pkg/controller/hyperconverged/hyperconverged_controller.go
> +}
I think it's can be combined into one function, then uses a single loop to delete them. WDYT?

2022-02-14 05:03 UTC, nunnatsa commented
/override coverage/coveralls

2022-02-14 05:03 UTC, nunnatsa approved these changes

2022-02-14 05:04 UTC, nunnatsa commented
/approve

2022-02-14 05:06 UTC, merged

2022-03-01 08:10 UTC, tiraboschi commented
/cherry-pick release-1.6