Make NonRoot feature gate configurable
kubevirt/hyperconverged-cluster-operator pull request #1894
Opened 2022-04-12 07:54 UTC by xpivarc

Fixes https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1846 where this feature should be still possible to opt-out

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
NONE
```

2022-04-12 11:27 UTC, xpivarc commented
/retest-required

2022-04-12 13:45 UTC, nunnatsa commented
@xpivarc, first, please run `make sanity` to make sure all the formatting is correct, the unit tests are passing and the deployment files are properly generated.

I'll try to find what went wrong in the E2E tests.

2022-04-21 13:14 UTC, xpivarc commented
> @xpivarc, first, please run `make sanity` to make sure all the formatting is correct, the unit tests are passing and the deployment files are properly generated.
> 
> I'll try to find what went wrong in the E2E tests.

@nunnatsa Unfortunately locally it fails with `Error: chdir: No such file or directory: OCI not found`

Any tips?

2022-04-25 17:52 UTC, xpivarc commented
PTAL @nunnatsa

2022-04-26 07:22 UTC, nunnatsa commented
Thanks @xpivarc - it's look good to me. Please just add a user guide in docs/cluster-configuration.md#featuregates.

2022-04-27 08:42 UTC, nunnatsa requested changes
Please add a user guide in docs/cluster-configuration.md#featuregates.

2022-04-27 12:03 UTC, nunnatsa approved these changes

2022-04-27 12:03 UTC, nunnatsa commented
/retest

2022-04-27 13:11 UTC, nunnatsa requested changes
Please update hack/check_defaults.sh to make the CI test pass. Take the latest output of the 
pull-hyperconverged-cluster-operator-e2e-k8s-1.23 lane as reference.

(I think it was handled in previous commit of this PR. I can't find it now and the tests are failing).

2022-04-27 13:18 UTC, xpivarc commented
> Please update hack/check_defaults.sh to make the CI test pass. Take the latest output of the pull-hyperconverged-cluster-operator-e2e-k8s-1.23 lane as reference.
> 
> (I think it was handled in previous commit of this PR. I can't find it now and the tests are failing).

Thanks!

2022-04-27 13:26 UTC, nunnatsa approved these changes

2022-04-28 12:39 UTC, nunnatsa commented
/override coverage/coveralls

2022-04-29 03:40 UTC, nunnatsa commented
/retest

2022-04-29 12:43 UTC, xpivarc commented
/test hco-e2e-upgrade-index-sno-azure
/test hco-e2e-upgrade-index-sno-aws

2022-04-29 13:51 UTC, merged