Provide better guidance for HCO on CRC
kubevirt/hyperconverged-cluster-operator pull request #2226
Opened 2023-02-01 16:55 UTC by tiraboschi

Provide better guidance for new users
that want to easilyand quickly try HCO on CRC.

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
NONE
```

2023-02-13 10:55 UTC, machadovilaca reviewed
My only concern is that maybe we are adding a big tool-specific section to the README. Personally, I would prefer to see you create a new file the in `docs/` folder with this guide and link it in the README.

2023-04-21 07:30 UTC, dharmit requested changes
Probably a few nits, but I think they are necessary in the docs.

2023-04-21 07:30 UTC, dharmit commented on README.md
> +Monitoring can be optionally enable with:
```suggestion
Monitoring can be optionally enabled with:
```

2023-04-21 07:30 UTC, dharmit commented on README.md
> +CRC runs as a VM, so in order to run Kubevirt on CRC to execute VMs with great performances you have to enable it.
```suggestion
CRC runs as a VM, so in order to run Kubevirt on CRC to execute VMs, you have to enable it.
```

2023-04-21 07:30 UTC, dharmit commented on README.md
> +For Intel processors, check the /sys/module/kvm_intel/parameters/nested file. For AMD processors, check the /sys/module/kvm_amd/parameters/nested file. If you see 1 or Y, nested virtualization is sup
```suggestion
For Intel processors, check the `/sys/module/kvm_intel/parameters/nested` file. For AMD processors, check the `/sys/module/kvm_amd/parameters/nested` file. If you see 1 or Y, nested virtualization is supported.
```

2023-04-21 07:30 UTC, dharmit commented on README.md
> +Nested virtualization is enabled until the host is rebooted. To enable it permanently, add `options kvm_amd nested=1` to /etc/modprobe.d/kvm.conf.
```suggestion
Nested virtualization is enabled until the host is rebooted. To enable it permanently, add `options kvm_amd nested=1` to `/etc/modprobe.d/kvm.conf`.
```

2023-12-02 18:33 UTC, closed without merging