[release-1.9]feat: add .snyk file
kubevirt/hyperconverged-cluster-operator pull request #2623
Opened 2023-11-23 10:08 UTC by ksimon1

feat: add .snyk file
This file is used for excluding vendor folders from snyk code scans
**Release note**:
```release-note
NONE
```

2023-11-23 16:21 UTC, tiraboschi requested changes

2023-11-23 16:21 UTC, tiraboschi commented on .snyk
> +    - tools/digester/vendor**
Also `tests/vendor`

2023-11-23 16:57 UTC, ksimon1 commented on .snyk
> +    - tools/digester/vendor**
fixed

2023-11-26 21:13 UTC, nunnatsa approved these changes
/approve

2023-11-26 21:15 UTC, merged