[operands] remove wasp-agent operand from HCO
kubevirt/hyperconverged-cluster-operator pull request #2901
Opened 2024-04-17 11:06 UTC by enp0s3

Signed-off-by: Igor Bezukh <ibezukh@redhat.com>

**What this PR does / why we need it**:
following the technical discussion we decided to deploy wasp agent in a different way, for the sake of easy transfer from wasp to kube swap.

-->
```release-note
Remove wasp-agent from being deployed by HCO
```

2024-04-17 12:11 UTC, tiraboschi commented
/retest

2024-04-17 14:23 UTC, tiraboschi requested changes

2024-04-17 14:23 UTC, tiraboschi commented on pkg/components/components.go
> -func GetWaspClusterRole() rbacv1.ClusterRole {
please drop also "daemonsets" get/list/watch/create/update/delete

2024-04-18 06:14 UTC, tiraboschi commented
/retest

2024-04-18 06:14 UTC, tiraboschi approved these changes

2024-04-18 10:08 UTC, tiraboschi commented
/retest

2024-04-18 12:20 UTC, tiraboschi commented
/retest

2024-04-18 12:20 UTC, tiraboschi commented
/approve

2024-04-18 14:10 UTC, tiraboschi commented
/retest

2024-04-18 17:27 UTC, tiraboschi commented
/retest

2024-04-19 08:58 UTC, tiraboschi commented
/retest

2024-04-22 10:23 UTC, tiraboschi commented
CI lanes for OKD are currently broken
/override ci/prow/okd-hco-e2e-upgrade-operator-sdk-aws
/override ci/prow/okd-hco-e2e-upgrade-operator-sdk-gcp

2024-04-22 10:24 UTC, merged

2024-05-08 20:16 UTC, stesrn commented
Verification of this patch is successful - https://main-jenkins-csb-cnvqe.apps.ocp-c1.prod.psi.redhat.com/job/openshift-virtualization-tests-runner/55/testReport/