Disable VMI migration upon K8s unschedulable taint
kubevirt/hyperconverged-cluster-operator pull request #823
Opened 2020-09-22 11:42 UTC by danielBelenky

Currently, the default behaviour is to migrate the VMI when a node is
tainted with the node.kubernetes.io/unschedulable key. This behaviour is
wrong and can be un-expected from the user's perspective because the
unschedulable taint means "do not schedule new workloads on this node"
and not "evict existing workloads from this node".

https://github.com/kubevirt/kubevirt/pull/4012 adds support for the
eviction API so we can properly handle node drains and specific
evictions on VMI pods.

This patch removes the default node drain key so we won't migrate VMIs
when we're not expected to do so.

Signed-off-by: Daniel Belenky <dbelenky@redhat.com>

**Release note**:

```release-note
VMIs will no longer migrate when node is tainted with node.kubernetes.io/unschedulable by default. Users can now use the proper node drain API to evacuate multiple VMIs from a node.
```

2020-09-22 11:42 UTC, danielBelenky commented
/hold

Waiting for https://github.com/kubevirt/kubevirt/pull/4012

2020-09-22 11:45 UTC, ovirt-infra commented
All tests passed

2020-09-22 11:51 UTC, tiraboschi requested changes
Please notice that virtconfig.MigrationsConfigKey is not reconciled so this is enough for new deployment but not for upgrades

2020-10-23 16:55 UTC, stu-gott approved these changes
/lgtm

2020-10-23 16:56 UTC, stu-gott commented
/hold cancel

2020-10-27 15:43 UTC, ovirt-infra commented
All tests passed

2020-10-27 15:47 UTC, tiraboschi commented
/cherry-pick release-1.2

2020-10-28 09:28 UTC, tiraboschi approved these changes

2020-10-28 09:43 UTC, nunnatsa approved these changes
/approve

2020-10-28 10:59 UTC, merged