fix run-local after it was broke
kubevirt/hyperconverged-cluster-operator pull request #924
Opened 2020-11-08 07:51 UTC by nunnatsa

Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**Release note**:

```release-note
NONE
```

2020-11-08 07:51 UTC, ovirt-infra commented
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

2020-11-08 08:56 UTC, orenc1 requested changes

2020-11-08 08:56 UTC, orenc1 commented on deploy/deploy.sh
> +kubectl config set-context --current --namespace=${hco_namespace}
There's a reason that command was removed last time - we don't want the context to be changed to `kubevirt-hyperconverged` namespace after the deployment is done. instead, we have `-n ${hco_namespace}` on every namespaced resource below.

2020-11-08 09:20 UTC, orenc1 approved these changes

2020-11-08 13:33 UTC, nunnatsa commented
/retest

2020-11-09 05:08 UTC, nunnatsa commented
/retest

2020-11-09 07:44 UTC, orenc1 commented
/retry

2020-11-09 08:03 UTC, orenc1 commented
/retest

2020-11-09 08:50 UTC, nunnatsa commented
Changed non-testable code:
/override coverage/coveralls

2020-11-09 13:14 UTC, orenc1 approved these changes

2020-11-09 13:17 UTC, nunnatsa commented
/approve

2020-11-09 13:33 UTC, merged